### ISSUE TITLE
Numerical issue with random walk for Dirichlet

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Bijectors.jl#12]
I've noticed a numeric issue when using this package with random walk algorithm. The code below is the minimal example to produce the bug:

```julia
using Distributions, Bijectors
dim = 10
dist = Dirichlet(dim, 2.0)
stepsize = 1e10
# Below gives DomainError with high probability
[logpdf_with_trans(dist, invlink(dist, link(dist, rand(dist)) .+ randn(dim) .* stepsize), true) for _ in 1:1_000]
```

I don't know if a stepsize of 10 is too high or not but it seems to be possible to have this kind of values during adaptation.

**Comment by yebai** [comment]
`stepsize` of `10` is quite big actually, did you look at adapted `epsilon` in HMC?

**Comment by xukai92** [comment]
Just checked - this happens when the step size is tuned to something like `5.75`.

**Comment by yebai** [comment]
I think NUTS adaption needs some further improvement. Before that happens, perhaps we can heuristically upper bound step size, e.g. `< 2`?

**Comment by xukai92** [comment]
> I think NUTS adaption needs some further improvement. Before that happens, perhaps we can heuristically upper bound step size, e.g. < 2?

2 still seems to be too high. 1 works.

> Dirichlet distribution is a very nasty one for transforms, I suspect it'll be hard to make it stable in all cases. If it occasionally throws off the edges, we can try to reject a Hamiltonian simulation.

Then we need to do a catch-exception which is slow. Alternatively we can make `logpdf_with_trans` return `-Inf` by checking terms inside `log` before evaluation?

**Comment by yebai** [comment]
> Then we need to do a catch-exception which is slow. Alternatively, we can make logpdf_with_trans return -Inf by checking terms inside log before evaluation?

Sounds good to me.

**Comment by mohamed82008** [comment]
We can just do `log(max(0, x))` everywhere there is `log(x)`. The output may then be `-Inf` or `NaN` if we divide 2 `Inf`s by each other for some reason. So outside we can check the output with `isnan` and `isinf`.

**Comment by yebai** [comment]
This sounds good to me. Perhaps give it a try and see whether it can fix #621?

**Comment by xukai92** [comment]
@yebai I will take a try today

**Comment by xukai92** [comment]
@mohamed82008 @yebai great it works
