### ISSUE TITLE
Readme confusing example

### ISSUE THREAD

**Issue by Ken-B** [TuringLang/Bijectors.jl#129]
The current Readme section on Functions is a bit confusing. 
In `1.` we get a value of `x = 0.7472542331020509`, but in `2.` the inverse gives `z = 0.6543406780096065` and claims `x == z`.

I find that depending on your luck (or precision), `x` will not always equal `z`:
```julia
julia> using Random; Random.seed!(42);

julia> x = rand(dist)
0.36888689965963756

julia> y = link(dist, x)
-0.5369949942509267

julia> z = invlink(dist, y)
0.36888689965963756

julia> x==z
true

julia> using Random; Random.seed!(43);

julia> x = rand(dist)
0.3885220158396991

julia> y = link(dist, x)
-0.45352911444046184

julia> z = invlink(dist, y)
0.38852201583969914

julia> x == z
false
```

Maybe use `\approx` to show ` x ≈ z`?

**Comment by torfjelde** [comment]
Good idea; opened a PR to do:) Thanks!
