### ISSUE TITLE
softplus bijector?

### ISSUE THREAD

**Issue by willtebbutt** [TuringLang/Bijectors.jl#132]
If someone has some time, a `softplus` Bijector would be cool to have.

**Comment by sethaxen** [comment]
This is provided now by LogExpFunctions's ChangesOfVariables extension:
https://github.com/JuliaStats/LogExpFunctions.jl/blob/a1c4fda2b9cc4c59c184648c0cfc7f694c415bf3/ext/LogExpFunctionsChangesOfVariablesExt.jl#L7-L10
