### ISSUE TITLE
rand call to dist of MvTransformed not using rng

### ISSUE THREAD

**Issue by JobJob** [TuringLang/Bijectors.jl#135]
Minor thing I noticed:

https://github.com/TuringLang/Bijectors.jl/blob/a3ece9122b8e1c9aa3f81105f6a384d85a09e856/src/transformed_distribution.jl#L134

should be:
```julia
res = hcat([td.transform(rand(rng, td.dist)) for i = 1:num_samples]...)
```

**Comment by torfjelde** [comment]
Ah, nice catch @JobJob !
