### ISSUE TITLE
invlink for simplex distributions

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Bijectors.jl#17]
Hi,

I've played around with the `invlink` function for simplex distributions and checked the correctness of the current implementation against the code used in Stan. (https://github.com/stan-dev/math/blob/502487c511594ccb93eb979df5b8fe163becb417/stan/math/rev/mat/fun/simplex_constrain.hpp)

The reimplementation I used is:

```Julia
function invlink_simplex(y::AbstractVector{T}) where {T<:Real}
    N = length(y)
    stick = one(T)
    x = zeros(T, length(y))
    for k in 1:(N-1)
        lk = map(T, log(N - k))
        z = logistic(y[k] - lk)
        x[k] = stick * z
        stick -= x[k]
    end
    x[N] = stick
    return x
end
```

and I found quite a bit of speed improvement if this implementation is used...

```
K = 1000
y = rand(K)
d = Dirichlet(K, 1.0)
​
@btime invlink_simplex(y);
@btime invlink(d, y);
  77.077 μs (1 allocation: 7.94 KiB)
  369.305 μs (1 allocation: 7.94 KiB)
```

Should I make a PR for this or do we think there are stability issues with the code?

**Comment by cpfiffer** [comment]
It looks to me like it's stable, but Mohammed the Master of Type Stability probably has a far better eye for that than me.

**Comment by mohamed82008** [comment]
Hi @trappmartin !

Your implementation looks type stable but I think we will run into numerical issues when inverting this. The main numerical stability problems were from `link`, `invlink` was just modified accordingly to be its inverse. I do think however there is a performance issue in Bijectors. I looked into it, and it seems the `@debug` sentences are causing some type instability. When removing them, and benchmarking I get:
```julia
julia> @btime invlink_simplex($y);                                                                                                                                             39.384 μs (1 allocation: 7.94 KiB)                                                                                                                                                                                                                                                                                                                      julia> @btime invlink($d, $y);                                                                                                                                                 43.395 μs (1 allocation: 7.94 KiB)
```
I assume the extra time is from the extra epsilon arithmetic that is done. The real difference is probably more when you use `@inbounds`. So I guess what it boils down to is if we are willing to throw away the inverse property between `link` and `invlink`, then we can gain some extra performance with your implementation of `invlink`.

**Comment by mohamed82008** [comment]
I will also make a PR to fix the `@debug` issues.

**Comment by trappmartin** [comment]
Sounds good. I wasn’t aiming for performance with my performance but was surprised that the invlink is so much slower.

**Comment by trappmartin** [comment]
Maybe as a side note, it might be good to have internal functions that do not require to pass a distribution object. This would allow a knowledgeable user to use the transformations without instantiating a Distributions object. Similar to the StatsFuns package.

**Comment by trappmartin** [comment]
One last note. I think the invlink should be as fast as my code. Your test shows that even after removing the `@debug` the invlink is still slower. I guess we should still think about improving the code as this gets called frequently during sampling.

**Comment by mohamed82008** [comment]
@trappmartin The slowdown is from the epsilons to make `invlink` a proper inverse of the numerically stable `link`. Are you proposing making `invlink` as fast as possible even if it is not a good inverse of the numerically stable `link`?

**Comment by trappmartin** [comment]
No, I propose we try to get to code faster while keeping it numerical stable.

**Comment by mohamed82008** [comment]
Done, #20. The main improvement came from replacing `log(1/x)` with `-log(x)` thus eliminating an unnecessary division.
