### ISSUE TITLE
`@debug` causing type instability and performance hit

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/Bijectors.jl#18]
It seems the `@debug` statements when expanded are causing a type instability and performance hit. ref: #17

**Comment by trappmartin** [comment]
Interesting finding. We might have this issue in Turings HMC too.

**Comment by mohamed82008** [comment]
Yes, I am thinking of using a constant global debug flag for this that can be set by setting an environment variable `ENV["DEBUG_TURING"] = 1` or `"DEBUG_BIJECTORS"`.
