### ISSUE TITLE
Fitting normalizing flow

### ISSUE THREAD

**Issue by danielward27** [TuringLang/Bijectors.jl#213]
Hi,

I planning on fitting a normalizing flow, but `Flux.params` is not extracting the parameters.

```
julia> using Bijectors, Flux, Tracker;
julia> d = MvNormal(zeros(2), ones(2));
julia> b = PlanarLayer(2, Tracker.param);
julia> td = transformed(d, b);
julia> Flux.params(td)
Params([])
```
Is this a bug or have I misunderstood the approach?

Versions:
- Julia version 1.7.1
- Bijections v0.1.3
- Flux v0.8.3
- Tracker v0.2.17

**Comment by torfjelde** [comment]
I think you've installed the wrong package https://github.com/scheinerman/Bijections.jl ? :sweat_smile:

**Comment by danielward27** [comment]
Oops! I reinstalled the packages in a new environment and it works fine (I think I had the correct package too, but an old version of Flux somehow). Thanks!
