### ISSUE TITLE
Can't apply Bijectors.ordered to TDist() and MvTDist()

### ISSUE THREAD

**Issue by boogiewoogit** [TuringLang/Bijectors.jl#287]
These should both work, but don't:
```
julia> using Turing
julia> Bijectors.ordered(filldist(TDist(1),2))
ERROR: ArgumentError: ordered transform is currently only supported for unconstrained distributions.
```

```
julia> using Turing
julia> Bijectors.ordered(MvTDist(1,zeros(2),Matrix(I(2))))
ERROR: MethodError: no method matching bijector(::MvTDist)
```

In particular TDist is supported on the real line and therefore unrestricted in the sense of this package:

[I have reported](https://github.com/TuringLang/Turing.jl/issues/2064) this to Turing.jl first, where it was identified that TDist's return type has the wrong support:

```
julia> bijector(TDist(1))
Bijectors.TruncatedBijector{Float64, Float64}(-Inf, Inf)
```

**Comment by Red-Portal** [comment]
Should have been addressed by #288 !
