### ISSUE TITLE
`TruncatedBijectors` not defined in `Distributions` extension

### ISSUE THREAD

**Issue by MilesCranmer** [TuringLang/Bijectors.jl#298]
Looks like it simply was not imported in this file: https://github.com/TuringLang/Bijectors.jl/blob/2402be2be1d572f1dabd02701c09369b68939e07/ext/BijectorsDistributionsADExt.jl#L54

**Comment by jae0** [comment]
very gently nudging this thread to see if we can accept the proposed fix as this error is breaking my work flow. Or alternatively, is there a simple way to do a temporary work-around with the proposed fix without creating a fork?

**Comment by penelopeysm** [comment]
Closed by #299
