### ISSUE TITLE
Add Tapir to Bijectors tests. 

### ISSUE THREAD

**Issue by yebai** [TuringLang/Bijectors.jl#316]
Let's add Tapir to the Bijectors tests. 

Related: https://github.com/TuringLang/AdvancedVI.jl/issues/63

**Comment by willtebbutt** [comment]
FWIW I'm also very happy to add an additional integration test suite to Tapir which runs Tapir on examples in Bijectors.jl, particularly if you have a handy list of functions that I can attempt to differentiate.
