### ISSUE TITLE
README links to dead docs

### ISSUE THREAD

**Issue by mhauru** [TuringLang/Bijectors.jl#317]
The README has a link to both dev and stable docs, but stable one is broken: https://turinglang.org/Bijectors.jl/stable

**Comment by devmotion** [comment]
https://github.com/TuringLang/Bijectors.jl/pull/262 was supposed to fix it. But it seems there exists no DOCUMENTER_KEY at all in Bijectors?!

**Comment by devmotion** [comment]
I added the key (and the matching deploy key). So now TagBot should be able to trigger the docs build.

**Comment by penelopeysm** [comment]
Fixed now
