### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/Bijectors.jl#72]
@JuliaRegistrator register()

**Comment by mohamed82008** [comment]
@JuliaRegistrator register()

**Comment by mohamed82008** [comment]
@JuliaRegistrator register()

**Comment by torfjelde** [comment]
@JuliaRegistrator register()

**Comment by mohamed82008** [comment]
@JuliaRegistrator register()

**Comment by mohamed82008** [comment]
I will close this issue and use commit messages to register new versions from now on. For example, https://github.com/TuringLang/Bijectors.jl/commit/24e8ff26613519b241383fd88ffad9a6feb96cf3.

**Comment by torfjelde** [comment]
I didn't see your message before I bumped the patch-version, so I'll do it here _one_ final time:

@JuliaRegistrator register()
