### ISSUE TITLE
TransformedDistributions should support maximum, minimum

### ISSUE THREAD

**Issue by arnavs** [TuringLang/Bijectors.jl#85]
Was testing these against the `UnivariateDistribution` fallback in `Expectations.jl`, but it fails because these methods aren't defined.

**Comment by arnavs** [comment]
Same for `params()`

**Comment by torfjelde** [comment]
I actually had a branch lying around with implementations for this:) But I didn't make it into a PR yet as it's slightly unclear to me whether or not `params` should return the parameters of the underlying distribution, i.e. `params(td.dist)`, or if it should also include parameters for the `Bijector`. If so, there's a fair bit of work and planning that needs to go into it. But, if users expect `params` to return only the parameters of the distribution, then this is no problem (see #86)

**Comment by arnavs** [comment]
That's a good point about `params.` Why not both? Ideally in a "flat" way, e.g. `mu, sigma, transformationstuff...`

**Comment by arnavs** [comment]
Closing as the PR was merged.
